-- EC_IT143_W4.2_basketball_s2_hs.sql
-- Step 2: Begin creating an answer
-- Answer path:
-- 1. Group BasketballPlayers by TeamID.
-- 2. Count the players in each group.
-- 3. Join the result to BasketballTeams so the team name is displayed.
-- 4. Turn the query into a reusable view.
-- 5. Store the result in BasketballPlayerCount.
-- 6. Reload the table through a stored procedure.
